services:
  - type: web
    name: minecraft-server
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    buildCommand: |
      echo "Build complete"
    startCommand: |
      echo "Start complete"
    envVars:
      - key: JAVA_HOME
        value: /usr/lib/jvm/java-17-openjdk-amd64
